### ISSUE TITLE
OSX Wallet 10.13.4  QT wallet issue

### ISSUE THREAD

**Issue by driscollco** [Moondex/MoonDEXCoin#3]
Process:               MoonDEX-Qt [34367]
Path:                  /Applications/MoonDEX-Qt.app/Contents/MacOS/MoonDEX-Qt
Identifier:            org.moondex.MoonDEX-Qt
Version:               2.0.0 (2.0.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           MoonDEX-Qt [34367]
User ID:               501

Date/Time:             2018-05-27 23:11:23.495 -0500
OS Version:            Mac OS X 10.13.4 (17E202)
Report Version:        12
Anonymous UUID:        B404A6C4-4958-6A57-15DE-5CD711DF28A6

Time Awake Since Boot: 280000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/MoonDEX-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

Binary Images:
       0x10aec8000 -        0x10c189ff3 +org.moondex.MoonDEX-Qt (2.0.0 - 2.0.0) <2E76DEAC-B75D-3BBC-AF85-5201D7B8FF7E> /Applications/MoonDEX-Qt.app/Contents/MacOS/MoonDEX-Qt
       0x10c964000 -        0x10c966fff +libboost_system.dylib (0) <5B6B032C-9090-3061-A99A-03B91F2E9D10> /Applications/MoonDEX-Qt.app/Contents/Frameworks/libboost_system.dylib
       0x10c96f000 -        0x10c97dfff +libboost_filesystem.dylib (0) <D6BE1D8F-6EDD-3C93-A34A-CFD8387ADFB7> /Applications/MoonDEX-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
       0x10c987000 -        0x10c9bafff +libboost_program_options-mt.dylib (0) <498E5D6A-87A0-3BAB-B44C-8159697314CD> /Applications/MoonDEX-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x10c9d9000 -        0x10c9e5fff +libboost_thread-mt.dylib (0) <187A420D-F69D-3B60-9971-A6C75F1367DD> /Applications/MoonDEX-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x10c9f1000 -        0x10c9f3fff +libboost_chrono-mt.dylib (0) <1DC25C3A-3A29-374D-8629-F580BC1C8BBE> /Applications/MoonDEX-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x10c9fb000 -        0x10cafeff3 +QtNetwork (0) <DD8EF1B7-0C03-386D-AE11-E618BC4C87F3> /Applications/MoonDEX-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x10cb45000 -        0x10cf71ff7 +QtWidgets (0) <AD15E490-1C7E-344F-9B40-A684A9160882> /Applications/MoonDEX-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10d0d9000 -        0x10d506ff7 +QtGui (0) <CED6B199-3797-3A04-818B-7A3C4944F330> /Applications/MoonDEX-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x10d604000 -        0x10dae5fff +QtCore (0) <0967D4C1-9487-3421-9861-304DEE848576> /Applications/MoonDEX-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x10db9a000 -        0x10dbf4ff7 +QtDBus (0) <6BFE4F79-D9C9-381E-A68D-BB5E6FFEDF4E> /Applications/MoonDEX-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x10dc12000 -        0x10dd44ff7 +libprotobuf.15.dylib (0) <F981F822-724D-3D6F-9451-282AD7D816B4> /Applications/MoonDEX-Qt.app/Contents/Frameworks/libprotobuf.15.dylib
       0x10ddf7000 -        0x10df1bff7 +libdb_cxx-4.8.dylib (0) <893E0F96-1F8A-3073-B1CF-CC60610C3E90> /Applications/MoonDEX-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x10df57000 -        0x10df96fff +libssl.1.0.0.dylib (0) <877B9435-C0CB-3AD2-9DB6-3D6FBC5B5CC2> /Applications/MoonDEX-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x10dfb3000 -        0x10e122b47 +libcrypto.1.0.0.dylib (0) <7206F3BE-315E-32FC-9923-3B6F38AF706C> /Applications/MoonDEX-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x10e18d000 -        0x10e195ffb +libminiupnpc.17.dylib (0) <A4D6BDCF-76CB-3E5E-907C-9DD22CCA0593> /Applications/MoonDEX-Qt.app/Contents/Frameworks/libminiupnpc.17.dylib
       0x10e19e000 -        0x10e19ffff +libevent_pthreads-2.1.6.dylib (0) <6F618640-46F3-3B56-A22C-26941B4D8790> /Applications/MoonDEX-Qt.app/Contents/Frameworks/libevent_pthreads-2.1.6.dylib
       0x10e1a3000 -        0x10e1d0fff +libevent-2.1.6.dylib (0) <891F379E-D5F9-39EB-BECA-2E24F943B7B3> /Applications/MoonDEX-Qt.app/Contents/Frameworks/libevent-2.1.6.dylib
       0x11c643000 -        0x11c68d9df  dyld (551.3) <AFAB4EFA-7020-34B1-BBEF-0F26C6D3CA36> /usr/lib/dyld
    0x7fff504cc000 -     0x7fff5132afff  com.apple.AppKit (6.9 - 1561.40.112) <C839B0C1-F7EE-3056-985C-63CF1A030EC4> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff5137c000 -     0x7fff5137cfff  com.apple.ApplicationServices (48 - 50) <8DA47D38-B07B-3AE2-B343-4579864430C6> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff52efb000 -     0x7fff53395ff7  com.apple.CoreFoundation (6.9 - 1452.23) <358C547D-E227-3228-8218-62327F4605C8> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff5407e000 -     0x7fff5407efff  com.apple.CoreServices (822.31 - 822.31) <615919A2-AE11-3F27-9A37-FB0CFF8D36B6> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff55066000 -     0x7fff5542cfff  com.apple.Foundation (6.9 - 1452.23) <E64540AD-1755-3C16-8537-552A00E92541> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff78a9a000 -     0x7fff78acdff7  libclosured.dylib (551.3) <DC3DA678-9C40-339C-A9C6-32AB74FCC682> /usr/lib/closure/libclosured.dylib
    0x7fff78fd4000 -     0x7fff78fd5ffb  libSystem.B.dylib (1252.50.4) <F64430FD-30A6-328D-A476-0AED41D371C6> /usr/lib/libSystem.B.dylib
    0x7fff7928b000 -     0x7fff792e1fff  libc++.1.dylib (400.9) <7D3DACCC-3804-393C-ABC1-1A580FD00CB6> /usr/lib/libc++.1.dylib
    0x7fff792e2000 -     0x7fff79306ff7  libc++abi.dylib (400.8.2) <EF5E37D7-11D9-3530-BE45-B986612D13E2> /usr/lib/libc++abi.dylib
    0x7fff7a705000 -     0x7fff7aaf63b7  libobjc.A.dylib (723) <BEEA51E2-1C4D-3672-87F6-F267B4AC6221> /usr/lib/libobjc.A.dylib
    0x7fff7b1c6000 -     0x7fff7b1caff7  libcache.dylib (80) <092479CB-1008-3A83-BECF-E115F24D13C1> /usr/lib/system/libcache.dylib
    0x7fff7b1cb000 -     0x7fff7b1d5ff3  libcommonCrypto.dylib (60118.50.1) <029F5985-9B6E-3DCB-9B96-FD007678C6A7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff7b1d6000 -     0x7fff7b1ddfff  libcompiler_rt.dylib (62) <968B8E3F-3681-3230-9D78-BB8732024F6E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff7b1de000 -     0x7fff7b1e7ffb  libcopyfile.dylib (146.50.5) <3885083D-50D8-3EEC-B481-B2E605180D7F> /usr/lib/system/libcopyfile.dylib
    0x7fff7b1e8000 -     0x7fff7b26dfff  libcorecrypto.dylib (562.50.17) <67007279-24E1-3F30-802D-A55CD5C27946> /usr/lib/system/libcorecrypto.dylib
    0x7fff7b2f5000 -     0x7fff7b32eff7  libdispatch.dylib (913.50.12) <848EEE57-4235-3A61-9A52-C0097DD2AB5E> /usr/lib/system/libdispatch.dylib
    0x7fff7b32f000 -     0x7fff7b34cff7  libdyld.dylib (551.3) <CF59A5A5-288B-30E6-BD42-9056B4E4139A> /usr/lib/system/libdyld.dylib
    0x7fff7b34d000 -     0x7fff7b34dffb  libkeymgr.dylib (28) <E34E283E-90FA-3C59-B48E-1277CDB9CDCE> /usr/lib/system/libkeymgr.dylib
    0x7fff7b35b000 -     0x7fff7b35bff7  liblaunch.dylib (1205.50.76) <4D52BB64-C568-3A36-8935-2480427EE2A2> /usr/lib/system/liblaunch.dylib
    0x7fff7b35c000 -     0x7fff7b360ffb  libmacho.dylib (906) <1902A611-081A-3452-B11E-EBD1B166E831> /usr/lib/system/libmacho.dylib
    0x7fff7b361000 -     0x7fff7b363ff3  libquarantine.dylib (86) <26C0BA22-8F93-3A07-9A4E-C8D53D2CE42E> /usr/lib/system/libquarantine.dylib
    0x7fff7b364000 -     0x7fff7b365ff3  libremovefile.dylib (45) <711E18B2-5BBE-3211-A916-56740C27D17A> /usr/lib/system/libremovefile.dylib
    0x7fff7b366000 -     0x7fff7b37dfff  libsystem_asl.dylib (356.50.1) <3B24F2D1-B578-359D-ADB2-0ED19A364C38> /usr/lib/system/libsystem_asl.dylib
    0x7fff7b37e000 -     0x7fff7b37efff  libsystem_blocks.dylib (67) <17303FDF-0D2D-3963-B05E-B4DF63052D47> /usr/lib/system/libsystem_blocks.dylib
    0x7fff7b37f000 -     0x7fff7b408ff7  libsystem_c.dylib (1244.50.9) <1187BFE8-4576-3247-8177-481554E1F9E7> /usr/lib/system/libsystem_c.dylib
    0x7fff7b409000 -     0x7fff7b40cffb  libsystem_configuration.dylib (963.50.8) <DF6B5287-203E-30CB-9947-78DF446C72B8> /usr/lib/system/libsystem_configuration.dylib
    0x7fff7b40d000 -     0x7fff7b410ffb  libsystem_coreservices.dylib (51) <486000D3-D8CB-3BE7-8EE5-8BF380DE6DF7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff7b411000 -     0x7fff7b412fff  libsystem_darwin.dylib (1244.50.9) <09C21A4A-9EE0-388B-A9D9-DFF8F6758791> /usr/lib/system/libsystem_darwin.dylib
    0x7fff7b413000 -     0x7fff7b419ff7  libsystem_dnssd.dylib (878.50.17) <9033B909-BCF7-37EB-A040-ADE8081611D6> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff7b41a000 -     0x7fff7b463ff7  libsystem_info.dylib (517.30.1) <AB634A98-B8AA-3804-8436-38261FC8EC4D> /usr/lib/system/libsystem_info.dylib
    0x7fff7b464000 -     0x7fff7b48aff7  libsystem_kernel.dylib (4570.51.2) <7FF1E390-2FAC-33A7-A545-60D9BB6692D4> /usr/lib/system/libsystem_kernel.dylib
    0x7fff7b48b000 -     0x7fff7b4d6fcb  libsystem_m.dylib (3147.50.1) <FC2E58BA-E6D5-3D2A-89CA-67F212294136> /usr/lib/system/libsystem_m.dylib
    0x7fff7b4d7000 -     0x7fff7b4f6fff  libsystem_malloc.dylib (140.50.6) <7FD43735-9DDD-300E-8C4A-F909A74BDF49> /usr/lib/system/libsystem_malloc.dylib
    0x7fff7b4f7000 -     0x7fff7b627ff3  libsystem_network.dylib (1229.51.2) <F65ED095-8ABA-3355-93F8-B9D0505932F4> /usr/lib/system/libsystem_network.dylib
    0x7fff7b628000 -     0x7fff7b632ffb  libsystem_networkextension.dylib (767.50.25) <758F1414-796D-3422-83C9-92D2915A06CE> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff7b633000 -     0x7fff7b63cff3  libsystem_notify.dylib (172) <08012EC0-2CD2-34BE-BF93-E7F56491299A> /usr/lib/system/libsystem_notify.dylib
    0x7fff7b63d000 -     0x7fff7b644ff7  libsystem_platform.dylib (161.50.1) <6355EE2D-5456-3CA8-A227-B96E8F1E2AF8> /usr/lib/system/libsystem_platform.dylib
    0x7fff7b645000 -     0x7fff7b650fff  libsystem_pthread.dylib (301.50.1) <0E51CCBA-91F2-34E1-BF2A-FEEFD3D321E4> /usr/lib/system/libsystem_pthread.dylib
    0x7fff7b651000 -     0x7fff7b654fff  libsystem_sandbox.dylib (765.50.51) <B48D256E-D7DB-3D4F-BC95-34557170C7AA> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff7b655000 -     0x7fff7b656ff3  libsystem_secinit.dylib (30) <DE8D14E8-A276-3FF8-AE13-77F7040F33C1> /usr/lib/system/libsystem_secinit.dylib
    0x7fff7b657000 -     0x7fff7b65eff7  libsystem_symptoms.dylib (820.50.37) <ED7350E0-B68B-374A-9AB7-DC1F195A8327> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff7b65f000 -     0x7fff7b672fff  libsystem_trace.dylib (829.50.17) <6568D68B-1D4C-38EE-90A9-54821D6403C0> /usr/lib/system/libsystem_trace.dylib
    0x7fff7b674000 -     0x7fff7b679ff7  libunwind.dylib (35.3) <BEF3FB49-5604-3B5F-82B5-332B80023AC3> /usr/lib/system/libunwind.dylib
    0x7fff7b67a000 -     0x7fff7b6a7fff  libxpc.dylib (1205.50.76) <25DB244E-217D-3CE0-A8F2-0C4255783B42> /usr/lib/system/libxpc.dylib

**Comment by MoondexDev** [comment]
This issue is fixed in v2.0.1.1 release.
